import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

import { Button, Stack, TextField } from "@mui/material";

import { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const CORRECT_PASSWORD = "DMIT2008A03";

export default function Home() {
  const [password, setPassword] = useState("");

  const [shouldShowSettings, setShouldShowSettings] = useState(false);

  const clickHandler = () => {
    console.log(password);

    if (password === CORRECT_PASSWORD) {
      setShouldShowSettings(true);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <TextField
            label="admin password"
            type="password"
            onChange={(event) => {
              setPassword(event.target.value);
            }}
            value={password}
          />
          <Button variant="contained" onClick={clickHandler}>
            Submit
          </Button>
          {shouldShowSettings && (
            <p>Replace me with the settings in the future</p>
          )}
        </main>
      </div>
    </>
  );
}
