import Head from "next/head";

import { Button, Container, Stack, TextField, Typography } from "@mui/material";

import { useState } from "react";

import Settings from "@/components/Settings";

const CORRECT_PASSWORD = "DMIT2008A03";

export default function Home() {
  const [password, setPassword] = useState("");

  const [shouldShowSettings, setShouldShowSettings] = useState(false);

  const clickHandler = () => {
    console.log(password);

    if (password === CORRECT_PASSWORD) {
      setShouldShowSettings(true);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <Container>
            <Stack direction="row" spacing={2}>
              <TextField
                label="admin password"
                type="password"
                onChange={(event) => {
                  setPassword(event.target.value);
                }}
                value={password}
              />
              <Button variant="contained" onClick={clickHandler}>
                Submit
              </Button>
            </Stack>
            {shouldShowSettings && (
              <Stack>
                <Settings colorOptions={["red", "blue", "green"]} />
                <Button
                  variant="contained"
                  onClick={() => {
                    setShouldShowSettings(false);
                  }}
                >
                  Hide Settings
                </Button>
              </Stack>
            )}
          </Container>
        </main>
      </div>
    </>
  );
}
