import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import exampleStyles from "../styles/Example.module.scss";

import SimpsonsCharacters from "../components/SimpsonsCharacters";

export default function Home() {
  let shouldRender = false;

  let shouldBeBlue = false;

  // This is a general ternary statement we are not using this variable anywhere
  let x = shouldBeBlue ? "in the true case" : "in the false case";

  let isInputValid = false;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
        <h1 className={shouldBeBlue ? exampleStyles["blue-background"] : ""}>
          The Component lists example.
        </h1>
        {shouldBeBlue ? (
          <p>Should be blue is true</p>
        ) : (
          <p>Should be blue is false</p>
        )}
        {shouldRender && <p>I was rendered</p>}
        <input className={isInputValid ? "" : exampleStyles["red-border"]} />
        <SimpsonsCharacters />
      </main>
    </div>
  );
}
