import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

// MUI Imports
import Container from "@mui/material/Container";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Grid from "@mui/material/Grid2";
import TextField from "@mui/material/TextField";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import Typography from "@mui/material/Typography";

// Import the useState
import { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  // Store the state of the textfield
  const [todoText, setTodoText] = useState("");

  // Store all the todos that exist
  const [allTodos, setAllTodos] = useState([]);

  // Called whenever the textfield is changed
  const onChangeHandler = (event) => {
    console.log(event.target.value);
    setTodoText(event.target.value);
  };

  // Called when the button is clicked
  const onAddTodoCLicked = () => {
    console.log("Add todo was clicked");

    // Use the spread operator to add todoText to allTodos
    let newAllTodos = [...allTodos, todoText];
    console.log(newAllTodos);

    // Update the todo list state
    setAllTodos(newAllTodos);

    // Reset the todoText field
    setTodoText("");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        // Link the style sheet for roboto font
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Container>
            <TextField
              id="todo-text-field"
              label="New ToDo"
              variant="filled"
              onChange={onChangeHandler}
              value={todoText}
            />
            <Button onClick={onAddTodoCLicked}>Add ToDo</Button>
            <List>
              {allTodos.map((todoItem, index) => {
                return (
                  <ListItem key={index}>
                    <ListItemText>
                      <Typography variant="p" component="div">
                        {todoItem}
                      </Typography>
                    </ListItemText>
                  </ListItem>
                );
              })}
            </List>
          </Container>
        </main>
      </div>
    </>
  );
}
